#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    expose:
       - 8000
    depends_on:
      - redis
    links:
      - redis:redis
    command: python /code/mysite/manage.py runserver 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx/
    depends_on:
      - web
    ports:
      - "80:80"
     #- "443:443"
   #volumes:
   #  - ./mysite/myapp/static:/static
    links:
      - web:web

  redis:
    image: redis:latest
    expose:
      - 6379


