# Generated by Django 2.1.7 on 2019-02-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190227_2343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDo',
            new_name='ToDoItem',
        ),
    ]
